### ISSUE TITLE
libovvc.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by dschien** [OpenVVC/OpenVVC#14]
Hi

I have followed the instructions to compile ffmpeg as per your README file.
Sadly, when I run `./ffplay` I am greeted with 
```
./ffplay: error while loading shared libraries: libovvc.so.1: cannot open shared object file: No such file or directory
```
I can see `libovvc.so.1` is present in `/usr/local/lib/libovvc.so.1`.

Any ideas how I can fix this?

Many thanks

**Comment by pcabarat** [comment]
Hi.
You can try setting your LD_LIBRARY_PATH environment variable to `/usr/local/lib/`before running ffplay : 

`export LD_LIBRARY_PATH=/usr/local/lib/`

This should permit ffplay to execute.

I will have a deeper look into why the linker does not find the library as soon as I have more time.

Pierre-Loup

**Comment by dschien** [comment]
That worked!
