### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by adamjw24** [OpenVVC/OpenVVC#4]
How would I build OpenVVC natively for Windows? What toolchain is required?

Best regards, Adam

**Comment by Jamaika1** [comment]
Hi Adam
Currently you won't build it on Windows. Some files will be inactive "nvcl_nal_vps.c".
You can create decoder, but it won't work with the latest version with jvetvvc or vvenc.

Best regards, Łukasz
https://www.sendspace.com/file/4ohpmy

**Comment by gugautie** [comment]
Hello Adam, 

We are using Cygwin or MSYS for building the library in Windows. Once the environment installed, the compilation steps are similar.
Last commit should correct some compilation errors.

Regards,

Guillaume

**Comment by adamjw24** [comment]
Thanks, I'll give it a go when back in the office.
